apiVersion: v1
kind: Service
metadata:
  name: kong-dp-metrics
  namespace: kong-dp-cpaws
  labels:
    app: kong-dp-metrics
spec:
  selector:
    app.kubernetes.io/instance: kong-dp-cpaws
    app.kubernetes.io/name: kong
  ports:
    - name: metrics
      port: 8100
      targetPort: 8100
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong-dp-metrics
  namespace: observability
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - kong-dp-cpaws
  selector:
    matchLabels:
      app: kong-dp-metrics
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
