apiVersion: v1
kind: Namespace
metadata:
  name: poc-support
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-oauth2
  namespace: poc-support
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-oauth2
  template:
    metadata:
      labels:
        app: mock-oauth2
    spec:
      containers:
        - name: mock-oauth2
          image: ghcr.io/navikt/mock-oauth2-server:2.1.0
          ports:
            - containerPort: 8080
          env:
            - name: JSON_CONFIG
              value: |
                {"interactiveLogin":true,"httpServer":"NettyWrapper","tokenCallbacks":[{"issuerId":"smg-poc","tokenExpiry":3600,"requestMappings":[{"requestParam":"grant_type","match":"client_credentials","claims":{"sub":"app-mobile","aud":"kong-gateway","scope":"mobile.read mobile.write","iss":"http://mock-oauth2.poc-support.svc.cluster.local:8080/smg-poc"}}]}]}
---
apiVersion: v1
kind: Service
metadata:
  name: mock-oauth2
  namespace: poc-support
spec:
  selector:
    app: mock-oauth2
  ports:
    - port: 8080
      targetPort: 8080
