apiVersion: v1
kind: Namespace
metadata:
  name: poc-backends
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mobile-mock-data
  namespace: poc-backends
data:
  response.json: |
    {
      "service": "mobile-login",
      "usrLoginName": "jperez",
      "userName": "Juan Perez",
      "password": "S3cr3t!2026",
      "email": "jperez@swissmedical.com.ar",
      "emails": ["jperez@smg.com.ar", "j.perez@gmail.com"],
      "token": "eyJhbGciOiJIUzI1Ni␣demo",
      "Authorization": "Bearer eyJ0eXAanon",
      "id": 884512,
      "numero": "20-31654987-3"
    }
  default.conf: |
    server {
      listen 8080;
      location / {
        default_type application/json;
        return 200 '{"see":"file"}';
        alias /data/response.json;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-mock
  namespace: poc-backends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-mock
  template:
    metadata:
      labels:
        app: mobile-mock
    spec:
      containers:
        - name: mobile-mock
          image: nginx:1.27-alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html/response.json
              subPath: response.json
            - name: conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: data
          configMap:
            name: mobile-mock-data
        - name: conf
          configMap:
            name: mobile-mock-data
---
apiVersion: v1
kind: Service
metadata:
  name: mobile-mock
  namespace: poc-backends
spec:
  selector:
    app: mobile-mock
  ports:
    - port: 80
      targetPort: 8080
