apiVersion: v1
kind: Namespace
metadata:
  name: poc-backends
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-mock
  namespace: poc-backends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-mock
  template:
    metadata:
      labels:
        app: mobile-mock
    spec:
      containers:
        - name: mobile-mock
          image: mendhak/http-https-echo:31
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: mobile-mock
  namespace: poc-backends
spec:
  selector:
    app: mobile-mock
  ports:
    - port: 80
      targetPort: 8080
