apiVersion: v1
kind: ConfigMap
metadata:
  name: sgi-mock-data
  namespace: poc-backends
data:
  index.html: |
    {
      "service": "sgi-core",
      "upb": "dXNlcjpwYXNzd29yZA==",
      "client_secret": "cs_live_9f8e7d6c5b4a3210",
      "base64Content": "JVBERi0xLjQKJeLjz9MKMyAwIG9iag==",
      "signature": "MEUCIQDx9kZ2demoSignatureValue==",
      "docu_nro": "31654987",
      "docu_tipo": "DNI",
      "documento": "DNI 31654987",
      "seguridad": "CVV-3829",
      "codigo": "SGI-00471"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgi-mock
  namespace: poc-backends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgi-mock
  template:
    metadata:
      labels:
        app: sgi-mock
    spec:
      containers:
        - name: sgi-mock
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: data
          configMap:
            name: sgi-mock-data
---
apiVersion: v1
kind: Service
metadata:
  name: sgi-mock
  namespace: poc-backends
spec:
  selector:
    app: sgi-mock
  ports:
    - port: 80
      targetPort: 80
